"""Add unique constraint to Card

Revision ID: 62fdf5d0a79e
Revises: 3f9a84fb86c1
Create Date: 2025-01-11 14:01:27.889013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62fdf5d0a79e'
down_revision: Union[str, None] = '3f9a84fb86c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_product', 'card', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_product', 'card', type_='unique')
    # ### end Alembic commands ###
