"""empty message

Revision ID: 88547a542af3
Revises: 4375a1bcd07d
Create Date: 2024-12-28 00:10:15.999656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88547a542af3'
down_revision: Union[str, None] = '4375a1bcd07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'count')
    # ### end Alembic commands ###
