"""UNIQUED COLUMN NAME IN PRODUCTS TABLE

Revision ID: c095dfa5eb68
Revises: 62fdf5d0a79e
Create Date: 2025-01-11 14:48:00.652785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c095dfa5eb68'
down_revision: Union[str, None] = '62fdf5d0a79e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'products', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    # ### end Alembic commands ###
